scala-exercises/exercises-scalatutorial

src/main/scala/scalatutorial/sections/ClassesVsCaseClasses.scala
src/main/scala/scalatutorial/sections/LazyEvaluation.scala
src/main/scala/scalatutorial/sections/StructuringInformation.scala
src/test/scala/scalatutorial/sections/ClassesVsCaseClassesSpec.scala

Fixes #5 Exercises with nothing to fill in / impossible to complete

#619 ScalaExercises 2º Part

---

src/main/scala/scalatutorial/sections/StandardLibrary.scala

Fixing typo in the Standard Library section

Fixing typo in Standard Library

---

src/test/scala/scalatutorial/sections/TypeClassesSpec.scala

There was a particularly flaky test in our set of exercises, regarding the Type Classes section. This exercises expects a function to perform an ordering in a list of rational numbers. As there are multiple versions of this function that could return a correct answer, our property testing is getting falsified results almost all runs (as it tries to offer false answers and will fail if a correct response is given).
Lacking a better solution, in this case I'm changing this test to use a straightforward application instead, to avoid issues with future changes and deployments.

Fixing flaky test

---

src/main/scala/scalatutorial/sections/FunctionalLoops.scala

As requested on #24.
Changing abs() to accept Double instead of Int in FunctionalLoops lesson, which solves compilation problems in isGoodEnough().
@jdesiloniz I needed another PR because I deleted my previous fork.

Changing abs() to accept Double instead of Int

---

src/main/scala/scalatutorial/sections/ClassesVsCaseClasses.scala
src/main/scala/scalatutorial/sections/ImperativeProgramming.scala
src/main/scala/scalatutorial/sections/ObjectOrientedProgramming.scala
src/main/scala/scalatutorial/sections/TypeClasses.scala
src/main/scala/scalatutorial/utils/BankAccount.scala
src/main/scala/scalatutorial/utils/IntSet.scala
src/main/scala/scalatutorial/utils/Note.scala
src/main/scala/scalatutorial/utils/Rational.scala
src/main/scala/scalatutorial/utils/animals.scala
src/main/scala/scalatutorial/utils/sorting.scala
src/test/scala/scalatutorial/sections/TypeClassesSpec.scala

This PR reorganizes a little bit the structure of this content library to avoid issues with Windows developers, as it seems that from Windows 7 the `aux` folder name is reserved and can't be used in the filesystem.
Suggested by @Tschis. Thanks!

Renaming the aux directory to avoid issues with Windows developers

---

src/main/scala/scalatutorial/sections/DefinitionsAndEvaluation.scala

The triangleArea returns values 6.0 not 6 for triangleArea(3, 4)

return type of triangle Area should be Double

---

src/main/scala/scalatutorial/sections/TypeClasses.scala

You have to add result type in order to call insertionSort as stated in "Calling Parameterized Sort".

Fix insertionSort function in TypeClasses.scala

---

src/main/scala/scalatutorial/sections/FunctionalLoops.scala

Fix comma splice.
ln58:   * We say, these expressions use “short-circuit evaluation”.   ->     * We say these expressions use “short-circuit evaluation”.

Grammar fix

---

src/main/scala/scalatutorial/sections/FunctionalLoops.scala

Explicitly call out that that we're evaluating the square root of 2 in example
of applying Newton's method.
---
It took me a bit to understand the variables at play in this example and though that more explicit documentation could help clarify here.

Clarify documentation of square root example

---

src/main/scala/scalatutorial/sections/StandardLibrary.scala

The sentence used to say "One difference with Try is that you can choose another type than Throwable to represent the exception," which makes it sound like you can choose types other than Throwable with Try when it is really talking about Either.

Fixing typos and making a sentence clearer

---

src/main/scala/scalatutorial/sections/TermsAndTypes.scala

- Adds a little extra guidance to last section
- I found myself trying to workout why `16.toHexString` wasn't "10", only to discover when I evaluated all the statements that that answer was fine, it was the second one which was `false` rather than `true` as `until` isn't inclusive.

Suggested more guidance in last section of Terms and Types

---

.travis.yml

* Use openjdk8 for Travis builds as oraclejkd8 is no longer supported in the default Linux image

Use openjdk8 for Travis builds

---

src/main/scala/scalatutorial/sections/LexicalScopes.scala

There's a typo in word redefined in Lexical Scope definition section

edit typo for redefined

---

src/main/scala/scalatutorial/sections/TermsAndTypes.scala

Due to the order of evaluation, 
1.to(10) == 1 gets evaluated to False
and the expression becomes
False to 10
Instead evaluation should be
1.to(10) == (1 to 10)

Rectified `to is not a member of Boolean` error

---

src/main/scala/scalatutorial/sections/TermsAndTypes.scala

When I run the following I get an error.
```
scala> 1.to(10) == 1 to 10
<console>:12: error: value to is not a member of Boolean
1.to(10) == 1 to 10
```
The expected result should be
```
scala> 1.to(10) == (1 to 10)
res5: Boolean = true
```
in my opinion.

Make the equality executable in the scala shell

---

build.sbt
project/ProjectPlugin.scala
src/main/scala/scalatutorial/sections/ScalaTutorialSection.scala

This PR updates ScalaTest dependency to version 3.1.0.

Updated ScalaTest 3.1.0

---

.travis.yml
build.sbt
project/ProjectPlugin.scala
project/build.properties
project/plugins.sbt
src/main/scala/scalatutorial/sections/FunctionalLoops.scala
src/main/scala/scalatutorial/sections/HigherOrderFunctions.scala
src/main/scala/scalatutorial/sections/LazyEvaluation.scala
src/main/scala/scalatutorial/sections/StandardLibrary.scala
src/main/scala/scalatutorial/sections/SyntacticConveniences.scala
src/main/scala/scalatutorial/sections/TailRecursion.scala
src/test/scala/scalatutorial/sections/FunctionalLoopsSpec.scala
src/test/scala/scalatutorial/sections/HigherOrderFunctionsSpec.scala
src/test/scala/scalatutorial/sections/LazyEvaluationSpec.scala
src/test/scala/scalatutorial/sections/TailRecursionSpec.scala
version.sbt

This PR updates the library to Scala 2.13.1 and some exercises to avoid deprecations.

Update to Scala 2.13.1

---

src/main/scala/scalatutorial/sections/PolymorphicTypes.scala

Add "type parameters" clarification on line 427.

Added missing words for contravariant bounding

---

src/main/scala/scalatutorial/sections/ImperativeProgramming.scala

Error: recursive method `iterate` needs result type

Fix recursive type missing error

---

src/main/scala/scalatutorial/sections/ImperativeProgramming.scala

To avoid the deprecation warning (since 2.13.0)

Convert int to string

---

src/main/scala/scalatutorial/sections/ObjectOrientedProgramming.scala

Method + in class Int is deprecated (since 2.13.0): Adding a number and a String is deprecated. Use the string interpolation `s"$num$str"`

Concatenate int and string (since Scala 2.13.0)

---

src/main/scala/scalatutorial/sections/SyntacticConveniences.scala

toList method was not properly written.

Updated SyntacticConveniences.scala

---

src/main/scala/scalatutorial/sections/SyntacticConveniences.scala

The tuple exercise is showing tuples to be represented with double parenthesis, but single parenthesis is enough

Remove double parenthesis in tuple exercise

---

src/main/scala/scalatutorial/sections/ClassesVsCaseClasses.scala

Replaces usage of the phrase "not the case" w/ "not true" since the word "case" is heavily used.  Also expands on what does happen to class parameters and adds a code snippet to demonstrate (I hope I conformed here stylistically?)
Raw REPL output ala
```
scala> class MyClass(x: Int) { def doubledX = x * 2}
defined class MyClass
scala> val myInstance = new MyClass(5)
myInstance: MyClass = MyClass@129b4fe2
scala> myInstance.doubledX
res0: Int = 10
scala> myInstance.x
<console>:14: error: value x is not a member of MyClass
myInstance.x
```
does not appear to be used anywhere

Explain parameter promotion in ClassesVsCaseClasses

---

src/main/scala/scalatutorial/sections/LexicalScopes.scala

Change 'defintion' to 'definition' in line 95
Line 130: Change 'there are more than one statements' to 'there is more than one statement'

Fix a spelling and a grammar error

---

src/main/scala/scalatutorial/sections/StandardLibrary.scala

The concepts of the head and tail of a list are used at line 100 without first being introduced. This change introduces the concepts earlier by making a minor addition at the introductory discussion of the constructor ::.

Introduce concepts of list head/tail before use

---

src/main/scala/scalatutorial/sections/LazyEvaluation.scala

The function `secondPrime` was accidentally outside of the code block, the small commit fixes that. Thanks for the great project!

Include secondPrime in code block
